CREATE TABLE IF NOT EXISTS audit_log_entries (
    chain_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id VARCHAR(36) NOT NULL UNIQUE,
    event_type VARCHAR(200) NOT NULL,
    actor_id VARCHAR(200) NOT NULL,
    resource_type VARCHAR(200) NOT NULL,
    resource_id VARCHAR(200) NOT NULL,
    payload_json TEXT NOT NULL,
    event_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    previous_hash VARCHAR(128) NOT NULL,
    event_hash VARCHAR(128) NOT NULL,
    payload_commitment VARCHAR(128) NOT NULL,
    field_commitments_json TEXT NOT NULL,
    field_salts_json TEXT NOT NULL,
    redacted_fields_json TEXT NOT NULL,
    archived_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_actor_id ON audit_log_entries(actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_resource_id ON audit_log_entries(resource_id);
CREATE INDEX IF NOT EXISTS idx_audit_event_timestamp ON audit_log_entries(event_timestamp);
